# Generated by Django 4.0.3 on 2022-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0002_alter_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L1', max_length=60),
        ),
    ]
